import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Group ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <header className="flex justify-center items-center gap-10 p-10">
        <nav> 
          <ul className=" flex gap-5">
            <li><a href="/Stays" className="hover:underline underline-offset-8">Stays</a></li>
            <li><a href="/flights" className="hover:underline underline-offset-8">Flights</a></li>
            <li><a href="/cars" className="hover:underline underline-offset-8">Car</a></li>
            <li><a href="/shop" className="hover:underline underline-offset-8">Shop</a></li>

          </ul>
        </nav>
      </header>
        {children}

        <footer>2025</footer>
      </body>
    </html>
  );
}
